//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVestigingVoorraad
    {
        public int PV_ID { get; set; }
        public int Product_ID { get; set; }
        public int Vestiging_ID { get; set; }
        public Nullable<int> Vestigingvoorraad { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Vestiging Vestiging { get; set; }
    }
}
