//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductVestigingVoorraads = new HashSet<ProductVestigingVoorraad>();
        }
    
        public int Product_ID { get; set; }
        public string Merk { get; set; }
        public string Model { get; set; }
        public string Naam { get; set; }
        public Nullable<int> Voorraad { get; set; }
        public Nullable<int> Gewicht { get; set; }
        public string Foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVestigingVoorraad> ProductVestigingVoorraads { get; set; }
    }
}
